---
- name: Install openshift-node Packages
  include: ./packages.yml
  tags:
    - install_openshift_node_packages

- name: Enable ntpd on openshift-node
  service: 
    name: "ntpd" 
    state: started 
    enabled: yes
  tags: 
    - enable_ntpd_on_host

- name: Install docker with storage for OpenShift
  include: ./install_docker_for_openshift.yml
  tags: 
    - install_docker_for_openshift
